export const FLOWER_LIST_REQUEST='FLOWER_LIST_REQUEST';
export const FLOWER_LIST_SUCCESS='FLOWER_LIST_SUCCESS';
export const FLOWER_LIST_FAIL='FLOWER_LIST_FAIL';

export const FLOWER_DETAILS_REQUEST='FLOWER_DETAILS_REQUEST';
export const FLOWER_DETAILS_SUCCESS='FLOWER_DETAILS_SUCCESS';
export const FLOWER_DETAILS_FAIL='FLOWER_DETAILS_FAIL';
