export const FRUIT_LIST_REQUEST='FRUIT_LIST_REQUEST';
export const FRUIT_LIST_SUCCESS='FRUIT_LIST_SUCCESS';
export const FRUIT_LIST_FAIL='FRUIT_LIST_FAIL';

export const FRUIT_DETAILS_REQUEST='FRUIT_DETAILS_REQUEST';
export const FRUIT_DETAILS_SUCCESS='FRUIT_DETAILS_SUCCESS';
export const FRUIT_DETAILS_FAIL='FRUIT_DETAILS_FAIL';
