export const VEGETABLE_LIST_REQUEST='VEGETABLE_LIST_REQUEST';
export const VEGETABLE_LIST_SUCCESS='VEGETABLE_LIST_SUCCESS';
export const VEGETABLE_LIST_FAIL='VEGETABLE_LIST_FAIL';

export const VEGETABLE_DETAILS_REQUEST='VEGETABLE_DETAILS_REQUEST';
export const VEGETABLE_DETAILS_SUCCESS='VEGETABLE_DETAILS_SUCCESS';
export const VEGETABLE_DETAILS_FAIL='VEGETABLE_DETAILS_FAIL';
